### ISSUE TITLE
command 'extension.relativePath' not found

### ISSUE THREAD

**Issue by Guillaume-Duval** [jakob101/RelativePath#10]
Hello,
Thank you for your plugin, it is very useful.
However, since the last update, it no longer works.

If I try to use it with CMD + Shift + H or via the command palette, I see the message "command 'extension.relativePath' not found."
I tried uninstalling and reinstalling but it is useless.

Regards

**Comment by jakob101** [comment]
Sorry about that. If you uninstall you should have the previous version. I'll fix it asap






On Thu, Sep 8, 2016 at 2:51 PM +0200, "Guillaume" <notifications@github.com> wrote:












Hello,

Thank you for your plugin, it is very useful.

However, since the last update, it no longer works.



If I try to use it with CMD + Shift + H or via the command palette, I see the message "command 'extension.relativePath' not found."

I tried uninstalling and reinstalling but it is useless.



Regards

**Comment by mahpah** [comment]
any update about this?

**Comment by Guillaume-Duval** [comment]
Thank you for your quick response @jakob101. 
I'll stay on the previous version pending the fix.

**Comment by hworld** [comment]
Hey, I'm not able to use current extension because of this issue, either. I couldn't figure out how to go to the previous version, though. Uninstalling it just removes it completely for me.

**Comment by jakob101** [comment]
Does the newest version work for you guys?

**Comment by NikosEfthias** [comment]
same here 
![](http://i.imgur.com/FzUikAM.png)

**Comment by jakob101** [comment]
Do you have 0.10.0? And have you restarted VSCode?






On Thu, Sep 15, 2016 at 9:57 AM +0200, "Nikos Efthias" <notifications@github.com> wrote:












same here

**Comment by NikosEfthias** [comment]
yes i had 0.10.0 and yesterday it didnt work and it still doesnt work @jakob101

**Comment by jakob101** [comment]
Which version of vscode are you using? It's tough to debug this.

**Comment by NikosEfthias** [comment]
1.5.2

**Comment by jakob101** [comment]
OS?

**Comment by NikosEfthias** [comment]
`ubuntu 16.4`

**Comment by qetee** [comment]
same here; hope @jakob101  fix this bug quickly

**Comment by jakob101** [comment]
Viggo you are on Ubuntu too? Tried a vm with win, pure osx and ubuntu. Can repro only on ubuntu.






On Fri, Sep 16, 2016 at 1:23 AM +0200, "Viggo" <notifications@github.com> wrote:












same here; hope @jakob101  fix this bug quickly

**Comment by jakob101** [comment]
Fixed in 0.11.0, please verify @qetee @NikosEfthias

**Comment by NikosEfthias** [comment]
its fixed for me @jakob101

**Comment by jakob101** [comment]
Amazing! Closing :) Thanks for help guys.

**Comment by alexpanchuk** [comment]
Same problem.
VSCode v1.18.1
RelativePath v1.0.0

Re-install etc. doesn't help
