### ISSUE TITLE
(new feature request) add a selector to directory

### ISSUE THREAD

**Issue by dev-xdyang** [jakob101/RelativePath#12]
When I write code like this:
<img width="333" alt="screen shot 2016-09-29 at 10 37 41 am" src="https://cloud.githubusercontent.com/assets/7471748/18939170/0ba219ee-8631-11e6-9632-e03154c6a46d.png">

I expect the path is:
<img width="444" alt="screen shot 2016-09-29 at 10 38 03 am" src="https://cloud.githubusercontent.com/assets/7471748/18939183/1a9a691a-8631-11e6-9368-0456972cbf04.png">
add path selector to directory may be usefule!

**Comment by jakob101** [comment]
Thanks! I will look into it. Cheers






On Thu, Sep 29, 2016 at 4:43 AM +0200, "阳小东" <notifications@github.com> wrote:












When I write code like this:





I expect the path is:



add path selector to directory may be usefule!

**Comment by jakob101** [comment]
Would you like to give it a shot in an PR?
