### ISSUE TITLE
[Feature request] Remove only some extensions

### ISSUE THREAD

**Issue by kristofferostlund** [jakob101/RelativePath#13]
Thanks for an awesome plugin!

When working with files of different types, for instance in Webpack when importing/requiring `.html`, `.js` and `.scss` files, it'd be nice to remove some extensions, while having others remain through the settings file, similar to how the `relativePath.ignore` setting works (possibly with include/exclude capabilities?). 

Example from code:
```javascript
const template = require('./app.template.html') // ./app.template.html
const helper = require('./app.helper') // ./app.helper.js
```

Example settings:
```json

{
    "relativePath.ignore": [
        "**/node_modules/**",
        "**/*.dll",
        "**/obj/**",
        "**/objd/**",
        "**/dist/**"
    ],
    "relativePath.removeLeadingDot": true,
    "relativePath.removeExtension": false,
    "relativePath.removeExtensions": [
        ".js",
        ".jsx"
    ],
    ...
  }
```

**Comment by jakob101** [comment]
Thanks @kristofferostlund. I see your point, might be a good next step :)

Wanna try it out and create a PR?

**Comment by kristofferostlund** [comment]
I'll give it a shot
