### ISSUE TITLE
In vsCode ，insert path without extension

### ISSUE THREAD

**Issue by herrdu** [jakob101/RelativePath#16]
When I chose a file in vsCode,   it always insert a path without Extension Name.   Like this:
    <script type="text/javascript" charset="UTF-8" src="<%=request.getContextPath() %>/plugins/sortableJs/Sortable.min"></script>

So ,how can get the full file name with  Extension Name?

Thank you

**Comment by jakob101** [comment]
Thanks @kristofferostlund! :)
@herrdu please close the issue if this is what you were looking for.

Jakob
