### ISSUE TITLE
command 'extension.relativePath' not found

### ISSUE THREAD

**Issue by alexpanchuk** [jakob101/RelativePath#19]
VSCode v1.18.1
RelativePath v1.0.0

Re-install etc doesn't help

**Comment by jakob101** [comment]
You closed it? Does that mean it's fixed?

**Comment by alexpanchuk** [comment]
Yes. It just start working. I don't know why.

**Comment by taoliujun** [comment]
> Yes. It just start working. I don't know why.

I can't active this plugin, however reinstall it or restart vscode.

i am cry. cry. -_-
