### ISSUE TITLE
Windows 10, user error?

### ISSUE THREAD

**Issue by edencorbin** [jakob101/RelativePath#2]
This extension would be very helpful to me, I installed, and can run Relative Path from the command pallet, but there is no output, either via visual code message or console. Any ideas?

**Comment by jakob101** [comment]
Hm, can you try with a file open and with the key command shift+ctrl+h?

I have the same configuration. Should work.

Let me know

**Comment by edencorbin** [comment]
I apologize for changing the thread slightly from the initial topic, what I am actually doing is developing a visual studio extension myself, currently I can write files to whatever project is opened by the end user, but only if they launch visual studio code from the command line, thereby making that folder the root for relative references. Would you by any chance, know a way around this, so I could reference (via my javascript extension execution) the opened project folder, even if visual studio was not launched via command line in that folder?

**Comment by jakob101** [comment]
I'm not sure there's a way around that, as I've never used the command line launcher. But I use node's relative path calculation tool, so you could as well. It can calculate relative paths from any file to any other. It might help.

**Comment by edencorbin** [comment]
Interesting, I'm familiar with __Dir but that's relative to the file executing the code, IE in my extension folder, any idea how I would get to the folder that happens to be open in the project?

**Comment by jakob101** [comment]
Nice :))
