### ISSUE TITLE
Files starting with a dot do not show up

### ISSUE THREAD

**Issue by chipit24** [jakob101/RelativePath#20]
On macOS, when I open the the file selector (`Cmd+Shift+H`), files that start with a dot (ex. `.env.test`) do not show up. These files are not listed in  the `relativePath.ignore` config or in my `.gitignore` file.

**Comment by rrag** [comment]
I did this

```diff
- this._myGlob = new Glob(this._workspacePath + "/**/*.*",
+ this._myGlob = new Glob(this._workspacePath + "/**/*",

- { ignore: this._configuration.get("ignore") },
+ { dot: true, ignore: this._configuration.get("ignore") },
```

and got the hidden files to work, @jakob101 do you see a problem with this change? if not I can do a PR

**Comment by jakob101** [comment]
Feel free to do this man! 👍 👍

**Comment by jakob101** [comment]
Just a small comment: please make sure you do get back only files, not folders. But otherwise we're good to go!
