### ISSUE TITLE
feature-request: new setting to prefix relative path with ./

### ISSUE THREAD

**Issue by gecharo** [jakob101/RelativePath#23]
I'm used to define relative paths prefixed with ./. It would be nice to have so settings for that.
Also displaing absolute path from current working folder when searching (it is more usefull when not using multispace). I'm not interest in where my project is located, just whats inside its scope.

Thanks

**Comment by jakob101** [comment]
Very interesting! We actually had that functionality before, and removed it. Wanna take a stab at adding that functionality?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gecharo** [comment]
I guess i could, just don't how much time i will have... Also not sure how to test changes in vscode itself. What is a basic workflow?

**Comment by jakob101** [comment]
Cool :)
