### ISSUE TITLE
Add option to omit specific string

### ISSUE THREAD

**Issue by ColCh** [jakob101/RelativePath#25]
Example:
I have file `src/foo/index.ts`
And I want to get relative path for it from `src/bar.ts`
I want to get relative path like `./foo`

In this case, `/index.ts` is omitted

So, this extension is amazing and I'm mind to open Pull Request for this feature.

But I need to discuss usage and api for it.

May be make it array of regs?

kinda

given
`config.omit = [ /\/index.ts$/ ]`, and relative path `src/foo/index.ts`
regexp in omit config will match string: `/index.ts`.
And so I will just remove it from resulting relative path. Result will be `src/foo`

What do you think @jakob101 ?

**Comment by jakob101** [comment]
Sounds great! :) feel free to post a PR
