### ISSUE TITLE
Trouble overriding relativePath.ignore

### ISSUE THREAD

**Issue by bearsnoozle** [jakob101/RelativePath#3]
Great extension!
I have trouble overriding the relativePath.ignore option.
I get error message: "Incorrect type. expected string[]"

![image](https://cloud.githubusercontent.com/assets/6557961/13761029/78f84c80-ea36-11e5-8364-5371ab09eef9.png)

Any ideas?

**Comment by jakob101** [comment]
Let me check it out a bit

**Comment by jakob101** [comment]
In User and Workspace settings I have this:

```
	// An array of glob keys to ignore when searching.
	"relativePath.ignore": [
		"**/node_modules/**",
		"**/*.dll",
		"**/obj/**",
		"**/objd/**"
	],
```

Can you check again? This looks similar to what you have.

**Comment by bearsnoozle** [comment]
Tried it on my Mac.
I still get the green squiggles where it says "incorrect type, expected string[]", but I can now find my node_modules files when I search, so it works.
Thanks

![screen shot 2016-03-15 at 21 01 48](https://cloud.githubusercontent.com/assets/6557961/13792252/47dbe2e0-eaf1-11e5-8a72-408fd67b7ad6.png)

**Comment by Terminux** [comment]
Hi

I have the same issue on my ubuntu.
If you remove the `ignore` word or just add a letter there is no more error

I hope it can help :smile:

**Comment by jakob101** [comment]
Thanks, I'll check out what's the weird issue :)






On Fri, Mar 18, 2016 at 2:29 AM -0700, "Castellant Guillaume" <notifications@github.com> wrote:












Hi



I have the same issue on my ubuntu.

If you remove the ignore word or just add a letter there is no more error



I hope it can help

**Comment by Terminux** [comment]
I think the `contributes.configuration.properties.type` have wrong format

**Comment by jakob101** [comment]
Published a new version that hopefully fixes this. Thanks!
