### ISSUE TITLE
is there a way to refress file cache

### ISSUE THREAD

**Issue by NikosEfthias** [jakob101/RelativePath#6]
when i add new files most of the times i cannot see them in the list how do i refresh the cache without restarting vscode

**Comment by jakob101** [comment]
If you add them through vscode they should be there. But through the filesystem, you will need to restart.






On Wed, Jun 22, 2016 at 7:53 AM +0200, "Nikos Efthias" <notifications@github.com> wrote:












when i add new files most of the times i cannot see them in the list how do i refresh the cache without restarting vscode
