### ISSUE TITLE
Option to leave out file extension

### ISSUE THREAD

**Issue by cliffkoh** [jakob101/RelativePath#8]
I often need the relative path to a file, which this extension does well, but without the file extension. It would be great if it is a configurable option that allows you to omit the file extension by default...

**Comment by sirajc** [comment]
when we use module loaders we have the option of omitting extensions in the code. Especially when we are using typescript. Extensions are not required in such cases. An option to leave out extension would be helpful

**Comment by jakob101** [comment]
Resolved as a setting in 0.9.2
