### ISSUE TITLE
Paths starts as `./../` instead of `../`

### ISSUE THREAD

**Issue by sirajc** [jakob101/RelativePath#9]
Paths starts as `./../` instead of `../`

expected:
should start with `../`

Relative Path: v0.8.0
VSCode: v1.4.0

**Comment by jakob101** [comment]
Resolved as a setting in 0.9.2

**Comment by sverrejoh** [comment]
Why is this a setting and not the default behaviour? `./..` should never occur, and "./"should always be stripped in this case.
